// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.9
// source: tests/proto/netserver.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение события
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tests_proto_netserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_netserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tests_proto_netserver_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_tests_proto_netserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_proto_netserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_tests_proto_netserver_proto_rawDescGZIP(), []int{1}
}

var File_tests_proto_netserver_proto protoreflect.FileDescriptor

const file_tests_proto_netserver_proto_rawDesc = "" +
	"\n" +
	"\x1btests/proto/netserver.proto\x12\x06events\"?\n" +
	"\x05Event\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x12\n" +
	"\x10SubscribeRequest2F\n" +
	"\fEventService\x126\n" +
	"\tSubscribe\x12\x18.events.SubscribeRequest\x1a\r.events.Event0\x01B\x03Z\x01.b\x06proto3"

var (
	file_tests_proto_netserver_proto_rawDescOnce sync.Once
	file_tests_proto_netserver_proto_rawDescData []byte
)

func file_tests_proto_netserver_proto_rawDescGZIP() []byte {
	file_tests_proto_netserver_proto_rawDescOnce.Do(func() {
		file_tests_proto_netserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_proto_netserver_proto_rawDesc), len(file_tests_proto_netserver_proto_rawDesc)))
	})
	return file_tests_proto_netserver_proto_rawDescData
}

var file_tests_proto_netserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_proto_netserver_proto_goTypes = []any{
	(*Event)(nil),            // 0: events.Event
	(*SubscribeRequest)(nil), // 1: events.SubscribeRequest
}
var file_tests_proto_netserver_proto_depIdxs = []int32{
	1, // 0: events.EventService.Subscribe:input_type -> events.SubscribeRequest
	0, // 1: events.EventService.Subscribe:output_type -> events.Event
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_proto_netserver_proto_init() }
func file_tests_proto_netserver_proto_init() {
	if File_tests_proto_netserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_proto_netserver_proto_rawDesc), len(file_tests_proto_netserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tests_proto_netserver_proto_goTypes,
		DependencyIndexes: file_tests_proto_netserver_proto_depIdxs,
		MessageInfos:      file_tests_proto_netserver_proto_msgTypes,
	}.Build()
	File_tests_proto_netserver_proto = out.File
	file_tests_proto_netserver_proto_goTypes = nil
	file_tests_proto_netserver_proto_depIdxs = nil
}
