global:
  cert_file:      ""
  cert_key:       ""
  
db:
  client:         "couchbase"
  conn_string:    "127.0.0.1"
  #client:         "sqlite3"
  #conn_string:    "/tmp/netmap.db"
  limit:          1000000
  username:       "couchbase"
  password:       "fvjPxwfcHP"

notifier:
  urls:           []
  
