global:
  cert_file:        ""
  cert_key:         ""
  
db:
  client:         "sqlite3"
  conn_string:    "/tmp/dbase.db"

cache:
  limit: 1000000
  flush_interval: "24h"

cluster:
  urls:           ["http://localhost:8082"]

notifier:
  urls:           ["http://localhost:9093"]
  
