global:
  cert_file:      ""
  cert_key:       ""
  
db:
  #client:         "redis"
  #conn_string:    "localhost:6379"
  client:         "sqlite3"
  conn_string:    "/tmp/netmap.db"
  limit:          1000000
  username:       ""
  password:       ""

notifier:
  urls:           []
