global:
  cert_file:      ""
  cert_key:       ""
  users:
  #  - username:     "test"
  #    password:     "test"
  #  - username:     "test1"
  #    password:     "test1"

db:
  client:         "sqlite3" #"mongo"
  conn_string:    "netmap.db" #"mongodb://localhost:27017"
  #name:           "netmap"
  #client:         "mysql"
  #conn_string:    ""
  
  #host:           "localhost:3306"
  limit:          1000000
  #username:       "root"
  #password:       "root"
  #for mongo
  # name:"netmap"
  # history_days: 30
  # limit: 1000000
  # bucket: ""
  # host: ""

collector:
  urls:           []
  path:           "/api/v1/netmap/records"
  prepare:        true
  username:       "test"
  password:       "test"

notifier:
  urls:           ["http://127.0.0.1:8086"]
  path:           "/api/v1/netmap/webhook"
