global:
  cert_file:      ""
  cert_key:       ""
  
db:
  #client:         "couchdb"
  #conn_string:    "127.0.0.1:5984"
  client:         "sqlite3"
  conn_string:    "/data/netmap.db"
  limit:          1000000
  username:       "admin"
  password:       "test"

notifier:
  urls:           []
