global:
  cert_file:      ""
  cert_key:       ""
  
db:
  client:         "sqlite3"
  #client:         "cache"
  conn_string:    "netmap.db"
  limit:          1000000
  flush_interval: "24h"

notifier:
  urls:           []
  
