[global]
urls = ["http://localhost:8084"]
content_encoding = "gzip"
account_id = 0

[netstat]
status = "disabled"
incoming = true
ignore_hosts = []
interval = "60s"

[connections]
command = "traceroute -m 3 -p {{ .port }} {{ .dst_name }}"
interval = "60s"
max_resp_time = "5s"