[global]
urls = ["http://localhost:8082"]
content_encoding = "gzip"

[netstat]
status = ""
ignore_ports = [22,1521]
interval = "900s"

[[connections]]
command = "traceroute -m 3 -p {{ .port }} {{ .dst_name }}"
interval = "60s"
max_resp_time = "5s"