[global]
urls = ["http://localhost:8082"]

[cache]
limit = 1000

[netstat]
enabled = true
send = true
status = ""
ignore_ports = [22]
interval = 60
command = "traceroute -m 3 -p {{ .port }} {{ .dst_name }}"

[[connections]]
urls = ["http://localhost:8082"]
command = "traceroute -m 3 -p {{ .port }} {{ .dst_name }}"
interval = 60