// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.9
// source: proto/netserver.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение события
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LocalAddr     *SockAddr              `protobuf:"bytes,5,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
	RemoteAddr    *SockAddr              `protobuf:"bytes,6,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	Relation      *Relation              `protobuf:"bytes,7,opt,name=relation,proto3" json:"relation,omitempty"`
	Options       *Options               `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_netserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetLocalAddr() *SockAddr {
	if x != nil {
		return x.LocalAddr
	}
	return nil
}

func (x *Event) GetRemoteAddr() *SockAddr {
	if x != nil {
		return x.RemoteAddr
	}
	return nil
}

func (x *Event) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *Event) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

// Вложенное сообщение
type SockAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SockAddr) Reset() {
	*x = SockAddr{}
	mi := &file_proto_netserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SockAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SockAddr) ProtoMessage() {}

func (x *SockAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SockAddr.ProtoReflect.Descriptor instead.
func (*SockAddr) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{1}
}

func (x *SockAddr) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SockAddr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SockAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Вложенное сообщение
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Result        int32                  `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	Response      float32                `protobuf:"fixed32,6,opt,name=response,proto3" json:"response,omitempty"`
	Trace         int32                  `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_proto_netserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{2}
}

func (x *Relation) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Relation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relation) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Relation) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Relation) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Relation) GetResponse() float32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *Relation) GetTrace() int32 {
	if x != nil {
		return x.Trace
	}
	return 0
}

// Вложенное сообщение
type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Timeout       float32                `protobuf:"fixed32,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxRespTime   float32                `protobuf:"fixed32,5,opt,name=maxRespTime,proto3" json:"maxRespTime,omitempty"`
	AccountID     uint32                 `protobuf:"varint,6,opt,name=accountID,proto3" json:"accountID,omitempty"`
	HostMask      string                 `protobuf:"bytes,7,opt,name=hostMask,proto3" json:"hostMask,omitempty"`
	IgnoreMask    string                 `protobuf:"bytes,8,opt,name=ignoreMask,proto3" json:"ignoreMask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_proto_netserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{3}
}

func (x *Options) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Options) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Options) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Options) GetTimeout() float32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Options) GetMaxRespTime() float32 {
	if x != nil {
		return x.MaxRespTime
	}
	return 0
}

func (x *Options) GetAccountID() uint32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *Options) GetHostMask() string {
	if x != nil {
		return x.HostMask
	}
	return ""
}

func (x *Options) GetIgnoreMask() string {
	if x != nil {
		return x.IgnoreMask
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_netserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{4}
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_proto_netserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_netserver_proto_rawDescGZIP(), []int{5}
}

func (x *ListObjectsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_netserver_proto protoreflect.FileDescriptor

const file_proto_netserver_proto_rawDesc = "" +
	"\n" +
	"\x15proto/netserver.proto\x12\x06events\"\xa2\x02\n" +
	"\x05Event\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12.\n" +
	"\tlocalAddr\x18\x05 \x01(\v2\x10.events.SockAddrR\tlocalAddr\x120\n" +
	"\n" +
	"remoteAddr\x18\x06 \x01(\v2\x10.events.SockAddrR\n" +
	"remoteAddr\x12,\n" +
	"\brelation\x18\a \x01(\v2\x10.events.RelationR\brelation\x12)\n" +
	"\aoptions\x18\b \x01(\v2\x0f.events.OptionsR\aoptions\"B\n" +
	"\bSockAddr\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\xaa\x01\n" +
	"\bRelation\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x16\n" +
	"\x06result\x18\x05 \x01(\x05R\x06result\x12\x1a\n" +
	"\bresponse\x18\x06 \x01(\x02R\bresponse\x12\x14\n" +
	"\x05trace\x18\a \x01(\x05R\x05trace\"\xeb\x01\n" +
	"\aOptions\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x02R\atimeout\x12 \n" +
	"\vmaxRespTime\x18\x05 \x01(\x02R\vmaxRespTime\x12\x1c\n" +
	"\taccountID\x18\x06 \x01(\rR\taccountID\x12\x1a\n" +
	"\bhostMask\x18\a \x01(\tR\bhostMask\x12\x1e\n" +
	"\n" +
	"ignoreMask\x18\b \x01(\tR\n" +
	"ignoreMask\"\x12\n" +
	"\x10SubscribeRequest\"2\n" +
	"\x12ListObjectsRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2\x82\x01\n" +
	"\fEventService\x12:\n" +
	"\vListObjects\x12\x1a.events.ListObjectsRequest\x1a\r.events.Event0\x01\x126\n" +
	"\tSubscribe\x12\x18.events.SubscribeRequest\x1a\r.events.Event0\x01B\x03Z\x01.b\x06proto3"

var (
	file_proto_netserver_proto_rawDescOnce sync.Once
	file_proto_netserver_proto_rawDescData []byte
)

func file_proto_netserver_proto_rawDescGZIP() []byte {
	file_proto_netserver_proto_rawDescOnce.Do(func() {
		file_proto_netserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_netserver_proto_rawDesc), len(file_proto_netserver_proto_rawDesc)))
	})
	return file_proto_netserver_proto_rawDescData
}

var file_proto_netserver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_netserver_proto_goTypes = []any{
	(*Event)(nil),              // 0: events.Event
	(*SockAddr)(nil),           // 1: events.SockAddr
	(*Relation)(nil),           // 2: events.Relation
	(*Options)(nil),            // 3: events.Options
	(*SubscribeRequest)(nil),   // 4: events.SubscribeRequest
	(*ListObjectsRequest)(nil), // 5: events.ListObjectsRequest
}
var file_proto_netserver_proto_depIdxs = []int32{
	1, // 0: events.Event.localAddr:type_name -> events.SockAddr
	1, // 1: events.Event.remoteAddr:type_name -> events.SockAddr
	2, // 2: events.Event.relation:type_name -> events.Relation
	3, // 3: events.Event.options:type_name -> events.Options
	5, // 4: events.EventService.ListObjects:input_type -> events.ListObjectsRequest
	4, // 5: events.EventService.Subscribe:input_type -> events.SubscribeRequest
	0, // 6: events.EventService.ListObjects:output_type -> events.Event
	0, // 7: events.EventService.Subscribe:output_type -> events.Event
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_netserver_proto_init() }
func file_proto_netserver_proto_init() {
	if File_proto_netserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_netserver_proto_rawDesc), len(file_proto_netserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_netserver_proto_goTypes,
		DependencyIndexes: file_proto_netserver_proto_depIdxs,
		MessageInfos:      file_proto_netserver_proto_msgTypes,
	}.Build()
	File_proto_netserver_proto = out.File
	file_proto_netserver_proto_goTypes = nil
	file_proto_netserver_proto_depIdxs = nil
}
