syntax = "proto3";

package events;

option go_package = ".";

service EventService {
  rpc ListObjects(ListObjectsRequest) returns (stream Event);
  rpc Subscribe(SubscribeRequest) returns (stream Event);
}

message Event {
  string serverId = 1;
  string event = 2;
  string id = 3;
  int64 timestamp = 4;
  SockAddr localAddr = 5;
  SockAddr remoteAddr = 6;
  Relation relation = 7;
  Options options = 8;
}

message SockAddr {
  string ip = 1;
  string name = 2;
  uint32 port = 3;
}

message Relation {
  string mode = 1;
  string type = 2;
  uint32 port = 3;
  string command = 4;
  int32 result = 5;
  float response = 6;
  int32 trace = 7;
  int32 ping = 8;          
  int32 packets = 9;       
  int32 packet_loss = 10;  
  float min_rtt = 11;      
  float max_rtt = 12;      
  float avg_rtt = 13;       
}

message Options {
  string service = 1;
  string status = 2;
  string command = 3;
  float timeout = 4;
  float maxRespTime = 5;
  uint32 accountID = 6;
  string hostMask = 7;
  string ignoreMask = 8;
  string src_info = 9;      
  string dst_info = 10;     
  string descriptions = 11; 
}

message SubscribeRequest {
  // Можно добавить фильтры или параметры подписки
}

message ListObjectsRequest {
  // Можно добавить фильтры или параметры подписки
  //int64 timestamp = 1;
}